name: Unzip Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip extract
        - uses: hoatruongdev09/extract-zip-github-action@v1.2
