name: Unzip Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: unzip "GetMoreRam-git.zip" -d extracted

      - name: Move files
        run: |
          shopt -s dotglob
          mv extracted/* .
          rm -rf extracted
          rm GetMoreRam-git.zip

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Extract project" || echo "Nothing to commit"
          git push
